### ISSUE TITLE
How to download CMeKG data?

### ISSUE THREAD

**Issue by FutureForMe** [Artessay/TC-RAG#3]
Hello, the work you have done is truly excellent and has given us a lot of inspiration. We would like to ask where we can download the CMeKG data that you used in your paper. I noticed that the URL(https://cmekg.pcl.ac.cn/) provided in the paper is no longer accessible.

**Comment by jiangxinke** [comment]
Hello, Haotian! Thank you so much for praising our work! We've also noticed the lack of accessibility of CMeKG—this dataset belongs to another group at Peking University, but it was still available for use when we downloaded it (while working on HyKGE). It seems to have gone closed-source again. Perhaps you could reach out to the authors of CMeKG for permission (since there might be copyright issues). If they agree, we’d be happy to share the integrated knowledge graph by us with you.

**Comment by jiangxinke** [comment]
This issue has been solved.
